pipeline {
    agent {
        label 'ws'
    }
    options {
        ansiColor('xterm')
    }
    parameters {
        
        choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Pick a Environment')
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select create or destroy')
        
        }
    
   stages{
    stage('terraform init') {
        steps {
            // when you intend to use any groovy commands or any syntax, enclose them inside script{}
            script { git branch; 'main', url: "https://github.com/SpandanaKopppaku/cart.git"}
            sh "terrafile -f env-${ENV}/Terrafile"
            sh "terraform init -backend-config=env-${ENV}/${ENV}-backend.tfvars"
            }
        }
    stage('terrafrom plan') {
        steps {
            sh "terraform plan -var-file=env-${ENV}/${ENV}.tfvars"
            }
        }
     stage('terrafrom apply') {
        steps {
            sh "terraform ${ACTION} -auto-approve -var-file=env-${ENV}/${ENV}.tfvars"
            }
        }
    }
}
       
    
 